/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TAREAS.vista;

import TAREAS.controlador.PartidoControl;
import java.time.DateTimeException;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author sebas
 */
public class VentanaPartido extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ventana
     */
    private PartidoControl PartidoControl = new PartidoControl();

    public VentanaPartido() {
        this.setClosable(true);
        this.setIconifiable(true);
        this.setResizable(true);
        this.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("codigo");

        jLabel2.setText("equipo 1");

        jLabel3.setText("equipo 2");

        jLabel4.setText("Fecha Partido (año/mes/dia)");

        jTextField1.setColumns(5);

        jTextField2.setColumns(10);

        jTextField3.setColumns(10);

        jTextField4.setColumns(5);

        jTextField5.setColumns(5);

        jTextField6.setColumns(5);

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Listar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(14, 14, 14)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Seguro de guardar datos?",
                "Sistema de equipos", JOptionPane.ERROR_MESSAGE,
                JOptionPane.QUESTION_MESSAGE) == 0) {
            var finaliza = false;
            while (finaliza == false) {

                try {
                    String[] data = new String[6];
                    data[0] = this.jTextField1.getText();
                    data[1] = this.jTextField2.getText();
                    data[2] = this.jTextField3.getText();
                    data[3] = this.jTextField4.getText();
                    data[4] = this.jTextField5.getText();
                    data[5] = this.jTextField6.getText();

                    this.PartidoControl.crear(data);
                    JOptionPane.showMessageDialog(this, "Se guardaron los datos",
                            "Aviso", JOptionPane.INFORMATION_MESSAGE);
                    finaliza = true;
                } catch (NumberFormatException el) {
                    JOptionPane.showMessageDialog(this, "Debe ingresar el formato requerido",
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
                catch (DateTimeException el) {
                
                JOptionPane.showMessageDialog(this, "Debe ingresar una fecha valida",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }break;

            }

        } else {

            JOptionPane.showMessageDialog(this, "No se guardaron los datos",
                    "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Seguro de listar los datos?",
                "Sistema de equipos", JOptionPane.ERROR_MESSAGE,
                JOptionPane.QUESTION_MESSAGE) == 0) {

            this.actualizarTabla();
            JOptionPane.showMessageDialog(this, "Se listaron los datos",
                    "Aviso", JOptionPane.INFORMATION_MESSAGE);

        } else {

            JOptionPane.showMessageDialog(this, "No se listar los datos",
                    "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    public void actualizarTabla() {

        var data = new Object[this.PartidoControl.listar().size()][4];
        for (var i = 0; i < this.PartidoControl.listar().size(); i++) {

            data[i][0] = this.PartidoControl.listar().get(i).getCodigo();
            data[i][1] = this.PartidoControl.listar().get(i).getEquipo1().getNombre();
            data[i][2] = this.PartidoControl.listar().get(i).getEquipo2().getNombre();
            data[i][3] = this.PartidoControl.listar().get(i).getFechaPartido().toString();

        }

        var encabezado = new String[4];
        encabezado[0] = "Código";
        encabezado[1] = "Equipo 1";
        encabezado[2] = "Equipo 2";
        encabezado[3] = "Fecha Partido";

        jTable1.setModel(new javax.swing.table.DefaultTableModel(data, encabezado));
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Seguro de modificar datos?",
                "Sistema de equipos", JOptionPane.ERROR_MESSAGE,
                JOptionPane.QUESTION_MESSAGE) == 0) {

            var finaliza = false;
            while (finaliza == false) {

                try {
                    String[] data = new String[7];
                    data[0] = this.jTextField1.getText();
                    data[1] = this.jTextField2.getText();
                    data[2] = this.jTextField3.getText();
                    data[3] = this.jTextField4.getText();
                    data[4] = this.jTextField5.getText();
                    data[5] = this.jTextField6.getText();
                    data[6] = this.jTextField1.getText();

                    this.PartidoControl.modificar(data);
                    JOptionPane.showMessageDialog(this, "Datos modificados",
                            "Aviso", JOptionPane.INFORMATION_MESSAGE);
                    finaliza = true;
                } catch (NumberFormatException el) {
                    JOptionPane.showMessageDialog(this, "Debe ingresar el formato requerido",
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
                catch (DateTimeException el) {
                
                JOptionPane.showMessageDialog(this, "Debe ingresar una fecha valida",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }break;

            }

        } else {

            JOptionPane.showMessageDialog(this, "No se modificaron los datos",
                    "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (JOptionPane.showConfirmDialog(this, "¿Seguro de eliminar los datos?",
                "Sistema de equipos", JOptionPane.ERROR_MESSAGE,
                JOptionPane.QUESTION_MESSAGE) == 0) {
            var finaliza = false;
            while (finaliza == false) {

                try {
                    var codigo = this.jTextField1.getText();
                    this.PartidoControl.eliminar(codigo);
                    this.actualizarTabla();

                    JOptionPane.showMessageDialog(this, "Se eliminaron los datos",
                            "Aviso", JOptionPane.INFORMATION_MESSAGE);
                    finaliza = true;
                } catch (NumberFormatException el) {
                    JOptionPane.showMessageDialog(this, "Debe ingresar el formato requerido",
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
                catch (DateTimeException el) {
                
                JOptionPane.showMessageDialog(this, "Debe ingresar una fecha valida",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }break;

            }

        } else {

            JOptionPane.showMessageDialog(this, "No se eliminaron los datos",
                    "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
